# Inventory & Order Management System — application container
#
# PHP version is LOCKED to 8.4.x by the project constitution and source spec §2.
# Do not bump this tag to 8.5 or drop it to 8.3: composer.json, this image, the CI
# commands, and the docs must all agree on 8.4.x.
FROM php:8.4-apache

# libonig-dev is required to build mbstring; default-mysql-client gives the container the
# `mysql` CLI so the README's schema/seed procedure can run from inside it.
RUN apt-get update && apt-get install -y --no-install-recommends \
        libonig-dev \
        default-mysql-client \
        unzip \
    && docker-php-ext-install -j"$(nproc)" pdo_mysql mbstring \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# fileinfo and json are compiled into the base image; pdo_mysql and mbstring are added above.

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Serve the front controller only. Nothing above public/ is reachable over HTTP —
# app/, config/, views/, database/ and .env all sit outside the document root.
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

# Apache configuration lives in real files under docker/ rather than being generated by a
# long printf, which is unreadable and — as this project found out — breaks silently when
# edited.
COPY docker/apache-vhost.conf /etc/apache2/sites-available/000-default.conf
COPY docker/apache-hardening.conf /etc/apache2/conf-available/zzz-hardening.conf
COPY docker/php.ini /usr/local/etc/php/conf.d/zzz-ioms.ini

RUN a2enmod rewrite headers \
    && a2enconf zzz-hardening

WORKDIR /var/www/html

# Install dependencies as their own layer so a source change does not re-resolve them.
#
# composer.lock is copied deliberately: without it the image resolves dependencies
# independently of the lock file, so the container could end up on different versions than
# the ones tested on a developer machine. With it, the build is reproducible.
COPY composer.json composer.lock ./

# COMPOSER_IPRESOLVE=4 forces IPv4. Inside a container repo.packagist.org resolves to an
# IPv6 address, but Docker's default bridge network has no IPv6 route, so the connection
# hangs until curl gives up ("curl error 28 ... Resolving timed out after 10001 ms").
# Pinning IPv4 is the documented Composer workaround for exactly this symptom, and it
# turned a 150-second timeout into a 5-second install.
ENV COMPOSER_PROCESS_TIMEOUT=600 \
    COMPOSER_NO_INTERACTION=1 \
    COMPOSER_IPRESOLVE=4

RUN composer install --no-scripts --no-autoloader --prefer-dist --no-progress

COPY . .
RUN composer dump-autoload --optimize

# Apache runs as www-data; only the upload directory needs to be writable by it.
RUN chown -R www-data:www-data /var/www/html/public/uploads \
    && find /var/www/html/public/uploads -type d -exec chmod 755 {} \;

EXPOSE 80
