sonar.projectKey=inventory-order-management-system
sonar.projectName=inventory-order-management-system

sonar.sources=app
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
    tests/**,\
    vendor/**,\
    storage/**,\
    bootstrap/cache/**,\
    app/Http/Controllers/Swagger/**

sonar.test.inclusions=tests/**